pid /tmp/cn_project_nginx.pid;
error_log /tmp/cn_project_error.log;

worker_processes 1;

events {
    worker_connections 1024;
}

http {
    access_log /tmp/cn_project_access.log;
    include /opt/homebrew/etc/nginx/mime.types;
    default_type application/octet-stream;
    sendfile on;

    # Backend cluster
    upstream backend_cluster {
        server 10.16.13.37:3001 max_fails=2 fail_timeout=5s; # Mohit (Mac 3)
        server 10.16.13.71:3002 max_fails=2 fail_timeout=5s; # Jayadeep (Mac 4)
    }

    # HTTP Server (Port 80)
    server {
        listen 80;
        server_name app.team1.test api.team1.test;

        location / {
            proxy_pass http://backend_cluster;
            proxy_set_header Host $host;
            proxy_set_header X-Real-IP $remote_addr;
            proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;

            proxy_pass_header X-Backend;
            proxy_pass_header Cache-Control;
            proxy_pass_header ETag;
        }
    }

    # HTTPS Server (Ports 443 & 8443)
    server {
        listen 443 ssl;
        listen 8443 ssl;
        server_name app.team1.test api.team1.test;

        ssl_certificate     /Users/akshith/Desktop/Computer_Networks_Project/certs/app.team1.test+1.pem;
        ssl_certificate_key /Users/akshith/Desktop/Computer_Networks_Project/certs/app.team1.test+1-key.pem;

        ssl_protocols TLSv1.2 TLSv1.3;

        location / {
            proxy_pass http://backend_cluster;
            proxy_set_header Host $host;
            proxy_set_header X-Real-IP $remote_addr;
            proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;

            proxy_pass_header X-Backend;
            proxy_pass_header Cache-Control;
            proxy_pass_header ETag;
        }
    }
}